name: cafebazaar_iab
description: Flutter plugin for cafe bazar in app billing
version: 0.0.3
author: Aref Hosseini <arefhosseini@yahoo.com>
homepage: https://github.com/arefhosseini/cafebazar_iab

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

flutter:
  plugin:
    androidPackage: ir.ayalma.cafebazaar_iab
    pluginClass: CafebazaarIabPlugin
    iosPrefix: FLT